### ISSUE TITLE
pip3 install deeplabcut fails to get hdf5 version

### ISSUE THREAD

**Issue by soheil-soltani** [DeepLabCut/Docker4DeepLabCut2.0#28]
Hi,

I'm trying to build deeplabcut for a non-Ubuntu machine (Linux Mint), which means non of the provided conda-env files are useful. So, I tried with 

`pip3 install deeplabcut`
which failed with the following error message:

```
Collecting deeplabcut
  Using cached deeplabcut-2.1.5.2-py3-none-any.whl (385 kB)
Collecting intel-openmp
  Using cached intel_openmp-2020.0.133-py2.py3-none-manylinux1_x86_64.whl (919 kB)
Collecting opencv-python~=3.4
  Using cached opencv_python-3.4.8.29-cp37-cp37m-manylinux1_x86_64.whl (28.3 MB)
Collecting ipython
  Downloading ipython-7.11.1-py3-none-any.whl (777 kB)
     |████████████████████████████████| 777 kB 3.2 MB/s 
Collecting pyyaml>=5.1
  Using cached PyYAML-5.3.tar.gz (268 kB)
Requirement already satisfied: setuptools in ./lib/python3.7/site-packages (from deeplabcut) (45.1.0)
Collecting statsmodels==0.10.1
  Using cached statsmodels-0.10.1-cp37-cp37m-manylinux1_x86_64.whl (8.1 MB)
Collecting chardet
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting moviepy
  Downloading moviepy-1.0.1.tar.gz (373 kB)
     |████████████████████████████████| 373 kB 11.8 MB/s 
Collecting requests
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
Collecting scipy
  Downloading scipy-1.4.1-cp37-cp37m-manylinux1_x86_64.whl (26.1 MB)
     |████████████████████████████████| 26.1 MB 11.1 MB/s 
Collecting h5py~=2.7
  Downloading h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 12.1 MB/s 
Collecting tables==3.4.3 
  Downloading tables-3.4.3.tar.gz (4.6 MB) 
     |████████████████████████████████| 4.6 MB 14.6 MB/s 
    ERROR: Command errored out with exit status 1: 
     command: /home/c3se/DLCut_virt_env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xs0d79ps/tables/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xs0d79ps/tables/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-xs0d79ps/tables/pip-egg-info 
         cwd: /tmp/pip-install-xs0d79ps/tables/ 
    Complete output (10 lines): 
    * Using Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
    * USE_PKGCONFIG: True 
    * Found conda env: ``/home/c3se/anaconda3`` 
    Traceback (most recent call last): 
      File "<string>", line 1, in <module> 
      File "/tmp/pip-install-xs0d79ps/tables/setup.py", line 597, in <module> 
        hdf5_version = get_hdf5_version(hdf5_header) 
      File "/tmp/pip-install-xs0d79ps/tables/setup.py", line 350, in get_hdf5_version 
        major_version = int(re.split("\s*", line)[2]) 
    ValueError: invalid literal for int() with base 10: 'd' 
    ---------------------------------------- 
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Any possible solution?

Thanks, and best regards,
Soheil

**Comment by MMathisLab** [comment]
Using Python 3.7.3 (default, Mar 27 2019, 22:11:17) 

Currently only python 3.6 is supported.

**Comment by MMathisLab** [comment]
note, that as of 2.1.6 3.7 is supported... I also added docs on how to create your own conda env, as all linux systems should be easy to do this on without issue, i.e. no need to use ours: https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md#creating-your-own-customized-conda-env
