### ISSUE TITLE
import deeplabcutcore failed 

### ISSUE THREAD

**Issue by bobfromjapan** [DeepLabCut/Docker4DeepLabCut2.0#32]
Hello.

I made deeplabcut environment on the AWS, centos7 instance by using new Dockerfile with deeplabcutcore command.

After struggles with installing nvidia-docker, I finally succeeded running deeplabcut docker container.

But I can't start deeplabcut in python script! It failed with importing error of deeplabcut or deeplabcutcore.
Here are the logs:

```
dlc@b2584f31192a:/$ python3
Python 3.6.3 (default, Oct  6 2017, 08:44:35)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'deeplabcut'

>>> import deeplabcutcore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/deeplabcutcore/__init__.py", line 20, in <module>
    from deeplabcutcore.create_project import create_new_project, create_new_project_3d, add_new_videos, load_demo_data
  File "/usr/local/lib/python3.6/dist-packages/deeplabcutcore/create_project/__init__.py", line 1, in <module>
    from deeplabcutcore.create_project.new import create_new_project
  File "/usr/local/lib/python3.6/dist-packages/deeplabcutcore/create_project/new.py", line 14, in <module>
    from deeplabcut import DEBUG
ModuleNotFoundError: No module named 'deeplabcut'
```

It seems the problem is deeplabcut module not existing.
Can I solve this problem with executing only 'pip install deeplabcut'? 
Or is this problem caused by my specific settings (AWS, centos7)?

If you have any suggestion about this problem, please give me some advice! 

Thank you and best regards.

**Comment by AlexEMG** [comment]
For update:
`pip install deeplabcutcore==0.0b2`

**Comment by bobfromjapan** [comment]
Thank you for your quick reply!

I tried new version of deeplabcutcore==0.0b2, but sadly I found same errors in other .py files!

```
dlc@b1a288cd7f9e:/$ pip3 install deeplabcutcore==0.0b2
Defaulting to user installation because normal site-packages is not writeable
Collecting deeplabcutcore==0.0b2
  Downloading deeplabcutcore-0.0b2-py3-none-any.whl (172 kB)
     |#                               | 10 kB 47.1 MB/s eta 0:00:01     |###                             | 20 kB 12.3 MB/s eta 0:00:01     |#####                           | 30 kB 16.7 MB/s eta 0:00:01     |#######                         | 40 kB 16.4 MB/s eta 0:00:01     |#########                       | 51 kB 11.6 MB/s eta 0:00:01     |###########                     | 61 kB 10.1 MB/s eta 0:00:01     |#############                   | 71 kB 9.5 MB/s eta 0:00:01     |###############                 | 81 kB 9.9 MB/s eta 0:00:01     |#################               | 92 kB 10.0 MB/s eta 0:00:01     |##################              | 102 kB 9.3 MB/s eta 0:00:01     |####################            | 112 kB 9.3 MB/s eta 0:00:01     |######################          | 122 kB 9.3 MB/s eta 0:00:01     |########################        | 133 kB 9.3 MB/s eta 0:00:01     |##########################      | 143 kB 9.3 MB/s eta 0:00:01     |############################    | 153 kB 9.3 MB/s eta 0:00:01     |##############################  | 163 kB 9.3 MB/s eta 0:00:01     |################################| 172 kB 9.3 MB/s 
Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from deeplabcutcore==0.0b2) (6.7)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from deeplabcutcore==0.0b2) (0.19.1)
...
        
...
Installing collected packages: deeplabcutcore
Successfully installed deeplabcutcore-0.0b2

dlc@b1a288cd7f9e:/$ python3
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcutcore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dlc/DeepLabCut/.local/lib/python3.6/site-packages/deeplabcutcore/__init__.py", line 20, in <module>
    from deeplabcutcore.create_project import create_new_project, create_new_project_3d, add_new_videos, load_demo_data
  File "/home/dlc/DeepLabCut/.local/lib/python3.6/site-packages/deeplabcutcore/create_project/__init__.py", line 2, in <module>
    from deeplabcutcore.create_project.new_3d import create_new_project_3d
  File "/home/dlc/DeepLabCut/.local/lib/python3.6/site-packages/deeplabcutcore/create_project/new_3d.py", line 15, in <module>
    from deeplabcut import DEBUG
ModuleNotFoundError: No module named 'deeplabcut'
```

Checking my installed `deeplabcutcore` codes (e.g.:`new_3d.py`, `demo_data.py`, `make_labeled_video.py ` etc), they have `import deeplabcut` or `import deeplabcut.xxx` lines. It seems woudn't work in my env, only installed deeplabcutcore.
How can I solve the problems?

I apologize my starange and incomprehensible English, but I really appreciate your kind supports!

Best regards.

**Comment by AlexEMG** [comment]
Thank you very much. There are indeed some issues! The deeplabcutcore is still in beta and here we should still be using deeplabcut, until these issues are sorted out.

**Comment by MMathisLab** [comment]
hi @bobfromjapan sorry for this - can you install `deeplabcut` for now, and we will work through the issues; you can pul l from the `testing` branch here, that has `deeplabcut` in the container, or `pip install deeplabcut`.

**Comment by bobfromjapan** [comment]
Thank you for replies!
I built the container from testing branch, and succeeded start deeplabcut training on my environment! Thank you so much!

I have bitter experiences on zebrafish video tracking many times... So when I read your Nature paper, I really excited for DLC's powerful tracking and pose estimation!
I hope that your excellent work will go well!
