### ISSUE TITLE
DLC 2.2.b7 Linux 18.04 (Ubuntu) - Docker: ImportError: cannot import name '_log'

### ISSUE THREAD

**Issue by rnrpereira** [DeepLabCut/Docker4DeepLabCut2.0#37]
Hi,
M system:

Linux Ubuntu 18.04
DLC 2.2.b7
RTX 2060

I'm getting the following error message after >> import deeplabcut as dlc :
`---> 20 from matplotlib.axes._axes import _log as matplotlib_axes_logger
     21 
     22 from deeplabcut.utils import auxiliaryfunctions

ImportError: cannot import name '_log'`

while I'm in Docker (btw: I updated DLC inside Docker).

**Comment by MMathisLab** [comment]
can you be sure that matplotlib is installed: inside the container: `pip install matplotlib==3.1.3`

**Comment by rnrpereira** [comment]
Thank you so much!
Didn't try this before because I had just updated DLC. 
But hat solved the problem...
Rodrigo

**Comment by rnrpereira** [comment]
Now, I start training and get this....

`Starting training....
iteration: 1000 loss: 0.0055 lr: 0.005
Exception in thread Thread-314:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rodrigo/DLC_Projects/.local/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 89, in load_and_enqueue
    batch_np = dataset.next_batch()
  File "/home/rodrigo/DLC_Projects/.local/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset_imgaug.py", line 298, in next_batch
    ) = self.get_batch()
  File "/home/rodrigo/DLC_Projects/.local/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset_imgaug.py", line 233, in get_batch
    image = imread(os.path.join(self.cfg.project_path, im_file), mode="RGB")
  File "/home/rodrigo/DLC_Projects/.local/lib/python3.6/site-packages/deeplabcut/utils/auxfun_videos.py", line 20, in imread
    return cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-qacpj5ci/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
`
